export default Captions = {
    login: "LOGIN",
    emailLabel: "Email",
    emailPlaceholder: "Enter email",
    emailValidation: "Enter a valid email",
    emailRequired: "Please enter a registered email",
    passwordLabel: "Password",
    passwordPlaceholder: "Enter password",
    passwordRequired: "Password is a required field",
    passwordValidation: "Must Contain 8 Characters, One Uppercase, One Lowercase, One Number and One Special Case Character",
    signUpForAccount: "Don't have an account? Sign Up",
    signUpForAccountConfirm: "Enter sign up verification code",
    forgottenPassword: "Forgotten password",
    accountNotVerifiedYet: "Account not verified yet",
    existingUser: "Existing user found. Please reset your password",
    incorrectEmailOrPassword: "Incorrect email or password",
    userDoesNotExist: "User does not exist. Please sign up",
    sendCode: "SEND CODE",
    backToLogin: "Back to Login",
    verificationCodeLabel: "Verification code",
    verificationCodeRequired: "Please enter your verification code",
    verificationCodePlaceholder: "Enter verification code",
    verificationCodeDoesNotExist: "Incorrect or expired verification code\n\nCode expires after 24 hours",
    verificationCodeAlreadyConfirmed: "User has already been confirmed\n\nPlease log in",
    confirmPasswordLabel: "Confirm password",
    confirmPasswordRequired: "Please confirm your password",
    confirmPasswordPlaceholder: "Confirm password",
    confirmPasswordVerification: "Passwords must match",
    confirmationCodePlaceholder: "Enter verification code",
    confirm: "CONFIRM",
    verify: "VERIFY",
    resendVerificationCode: "Resend Verification Code",
    passwordsDoNotMatch: "Passwords do not match!",
    signUp: "SIGN UP",
    tagline: "Organization on the go",
    infrastructureError: "Our apologies, our infrastructure provider is experiencing issues.\n\nPlease try using the application later.",
    errorApology: "Apologies, we have experienced an error",
    appName: "Task Master",
    loginUnavailable: "No internet connection - login unavailable",
    editingUnavailable: "No internet connection - no editing available",
    logout: "Logout",
    newTask: "New Task",
    editTask: "Edit Task",
    taskLabel: "Task",
    taskPlaceholder: "Enter task",
    taskRequired: "Please enter your task",
    taskSave: "SAVE",
    taskCreate: "CREATE",
    taskCancel: "Cancel",
    dueDateLabel: "Due date",
    dueDatePlaceholder: "Select due date",
    dueDateRequired: "Please enter the task due date",
    dueDateConfirm: "Confirm",
    dueDateCancel: "Cancel",
    noTasksGetStarted: "You have no tasks!\n\nCreate a task to get started...",
    noLateTasks: "You have no late tasks...\n\nwell done!",
    todoTasksTitle: "To do tasks:",
    lateTasksTitle: "Late tasks:",
    allTasksTitle: "All tasks - completed & late:"
  };